"""Add image_data to expense_items

Revision ID: 590a5f50c2c8
Revises: 58b71595aa52
Create Date: 2026-02-11 17:50:52.337474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590a5f50c2c8'
down_revision: Union[str, Sequence[str], None] = '58b71595aa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_items', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_items', 'image_data')
    # ### end Alembic commands ###
