"""add_user_id_scoping

Revision ID: 5f8d21454dc0
Revises: feea34a09dce
Create Date: 2026-02-13 10:27:47.699567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8d21454dc0'
down_revision: Union[str, Sequence[str], None] = 'feea34a09dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_friends_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.drop_index(op.f('ix_saved_items_name'))
        batch_op.create_index(op.f('ix_saved_items_name'), ['name'], unique=False)
        batch_op.create_foreign_key('fk_saved_items_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_saved_items_users', type_='foreignkey')
        batch_op.drop_index(op.f('ix_saved_items_name'))
        batch_op.create_index(op.f('ix_saved_items_name'), ['name'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('fk_friends_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
