"""add_user_profile_fields

Revision ID: d32776676e51
Revises: 5f8d21454dc0
Create Date: 2026-02-13 13:04:40.712584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32776676e51'
down_revision: Union[str, Sequence[str], None] = '5f8d21454dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subtitle')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
